### PR TITLE
Hide "More" button on private sites

### LINKED ISSUE #306: Load More button: does not handle private blog
**Describe the bug**
When you activate the Load More button on the block, it doesn't load the posts, it shows the message _"Something went wrong. Please refresh the page and/or try again"_.

**To Reproduce**
1. Go to Pages and create a new page
2. Add the Blog Posts block
3. Activate the option _"Show "More" Button"_ on the block
4. Publish the page

**Screenshots**
When you click on the button to load more posts, this is what shows up, including the errors on the console:

BlogPostsBlock

**Expected behavior**
To load more posts.

### PR DESCRIPTION
**Pull request by WunderBart**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #306.

The "More" button request is returning 403 (Forbidden) when the site is set as `Private` in WP.com settings:

image

Because there's no straightforward way of authenticating the request from the view side of the blog (see https://github.com/Automattic/newspack-blocks/pull/347#issuecomment-585883729), we've decided to hide the button in both the editor and view sides.

### How to test the changes in this Pull Request:

This is a bit complicated because it depends on a WP.com blog property, so I recommend the following:

Editor testing:

1. Create page
2. In the JS console, run `window.wpcomGutenberg.blogPublic = '-1'`
3. Add Newspack Articles block
4. There should not be the `Show "More" button` option available

View testing:

1. Manually set [`$is_blog_private`](https://github.com/Automattic/newspack-blocks/blob/fix/handle-private-blog-load-more/src/blocks/homepage-articles/view.php#L90) to true
2. Publish & go to a page containing the Articles block with the "More" button enabled
3. There should not be the "More" button on the page

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by WunderBart** [comment]
@obenland @apeatling @jeffersonrabb I haven't tested manually this one yet (pretty sure the implementation is solid, tho), but I'm wondering if this would be the best direction - should we continue with suppressing the button for private sites or rather focus on getting the request authenticated? FYI, I've already tried setting the `X-WP-Nonce` to do the latter but got `Request header field x-wp-nonce is not allowed by Access-Control-Allow-Headers in preflight response`, so I'd appreciate any feedback here 🙏

**Comment by claudiulodro** [comment]
AFAIK the change has been made so the button should be working on WPCOM now. This may not be needed any more?

**Comment by WunderBart** [comment]
I've just tried using "Load More" on my private site and it's still not working. Could you point me to that change please, @claudiulodro?

File: src/blocks/homepage-articles/edit.js [hunk 1]
```diff
@@ -336,6 +337,16 @@ class Edit extends Component {
...
+							help={
+								<>
+									{ __( 'The button will not be displayed on private sites. ' ) }
+									{
+										<ExternalLink href="https://en.support.wordpress.com/settings/#general">
+											{ __( 'More information' ) }
+										</ExternalLink>
+									}
+								</>
+							}
```
Comment (obenland) [inline src/blocks/homepage-articles/edit.js]: Rather than adding that help text, let's just not even show that option on private sites.

**Comment by obenland** [comment]
This approach would be a bandaid over the bug but it doesn't fix the cause of it. Can we try finding a way to authenticate the API request?

**Comment by WunderBart** [comment]
>This approach would be a bandaid over the bug but it doesn't fix the cause of it. Can we try finding a way to authenticate the API request?

@obenland, I couldn't find an obvious way of authenticating this request (see https://github.com/Automattic/newspack-blocks/pull/347#issuecomment-578224942, https://github.com/Automattic/newspack-blocks/issues/306#issuecomment-583372932 & https://github.com/Automattic/newspack-blocks/issues/306#issuecomment-585874324). The `admin-ajax.php` solution would be worth checking but it's a larger task and for now, I would resolve this edge case by hiding the option for private sites after all. How does that sound? cc @jeffersonrabb @claudiulodro

**Comment by obenland** [comment]
Yeah, let's hide the option in the editor on private sites

File: src/blocks/homepage-articles/edit.js (hunk 1 above)
Comment (WunderBart) [reply src/blocks/homepage-articles/edit.js]: > Rather than adding that help text, let's just not even show that option on private sites.

I couldn't find any `isBlogPublic/Private` flag available in the client (editor) and I can't really find a _non-invasive_ way of passing the `blog_public` variable from the back-end either. If we decide that hiding the feature in the editor is necessary, then we could probably consider creating a script tag and assigning the flag globally (the _invasive_ way). What do you think?

> That would also avoid the change in view.php.

Can we actually avoid making a change in `view.php`? If a page already has the block on with `Load More` enabled and then makes the site private, if we disable it in the editor it would still display in the view, wouldn't it?

/cc @jeffersonrabb

Comment (jeffersonrabb) [reply src/blocks/homepage-articles/edit.js]: > Can we actually avoid making a change in view.php? If a page already has the block on with Load More enabled and then makes the site private, if we disable it in the editor it would still display in the view, wouldn't it?

Yeah, I agree, I think you still need to suppress the feature in `view.php`.

File: src/blocks/homepage-articles/edit.js [hunk 2]
```diff
@@ -5,6 +5,7 @@
  */
 import QueryControls from '../../components/query-controls';
 import { STORE_NAMESPACE } from './store';
+import { getIsBlogPrivate } from './helpers';
```
Comment (obenland) [inline src/blocks/homepage-articles/edit.js]: Instead of creating a helper function, what do you think of defining a variable in `render()` based on whether the global is available and has the desired value? It would decrease the overhead quite a bit.

File: src/blocks/homepage-articles/edit.js [hunk 3]
```diff
@@ -331,7 +332,7 @@ class Edit extends Component {
 							required
 						/>
 					) }
-					{ ! specificMode && (
+					{ ! specificMode && getIsBlogPrivate() !== true && (
```
Comment (obenland) [inline src/blocks/homepage-articles/edit.js]: Since it doesn't matter whether it's a boolean or not, these checks can be just implicit

File: src/blocks/homepage-articles/view.php [hunk 4]
```diff
@@ -13,6 +13,8 @@
  * @return string Returns the post content with latest posts added.
  */
 function newspack_blocks_render_block_homepage_articles( $attributes ) {
+	$is_blog_private = defined( 'IS_BLOG_PRIVATE' ) && IS_BLOG_PRIVATE;
```
Comment (obenland) [inline src/blocks/homepage-articles/view.php]: Where is this constant being defined? Can we not use the option here?

Comment (WunderBart) [reply src/blocks/homepage-articles/view.php]: The [constant will be defined in BPB](https://github.com/Automattic/wp-calypso/pull/39509/commits/22618082d437e13e06f91b6877c1ee9d47593a40), same as [the client-side one](https://github.com/Automattic/wp-calypso/pull/39509/commits/a231e26c1e2d8ba53a7c5a63d00e844373911ac6). I wasn't sure if it's OK to directly use `wpcom` options here, but if it is I think we can also drop the mapping of the client-side one. What do you think?

Comment (marekhrabe) [reply src/blocks/homepage-articles/view.php]: I think it is safe to use the direct option instead of the constant. `blog_public` is actually a built-in site option of WordPress so it will be always present.

Documentation for `blog_public` https://developer.wordpress.org/apis/handbook/options/#privacy

The only part that is specific for wpcom is the addition of the third possible value `-1` which means "private".

Comment (WunderBart) [reply src/blocks/homepage-articles/view.php]: Ah, that makes a lot of sense. Will use the `blog_public` instead then. Thanks, @marekhrabe!

File: src/blocks/homepage-articles/edit.js (hunk 2 above)
Comment (WunderBart) [reply src/blocks/homepage-articles/edit.js]: The `private` flag is needed in 2 different `render`s - IMO it's best to have it in a separate function. I decided to move it to a separate file as this one is already quite heavy.

File: src/blocks/homepage-articles/edit.js [hunk 5]
```diff
@@ -633,8 +641,9 @@ class Edit extends Component {
 						{ latestPosts && latestPosts.map( post => this.renderPost( post ) ) }
 					</div>
 				</div>
-
-				{ ! specificMode && latestPosts && moreButton && (
+				{ ! specificMode && latestPosts && moreButton && ! getIsBlogPrivate() && (
+					// The "More" button option is hidden for private sites, so we should
+					// also hide the button in case it was previously enabled.
```
Comment (WunderBart) [inline src/blocks/homepage-articles/edit.js]: Decided to go with inline comments because linter kept requiring a `@param` definition here for some reason when I used a block comment.

Comment (retrofox) [reply src/blocks/homepage-articles/edit.js]: I think you can do it removing one `*` from the first line.

```
/*
 * Use this structure for generic doc block
 */
```

```
/** <- use double for functions/methods/etc
 *
 */
```

File: src/blocks/homepage-articles/helpers.js [hunk 6]
```diff
@@ -0,0 +1,10 @@
+/**
+ * Based global WP.com blog_public option, checks whether current blog is
+ * private or not.
+ *
+ * @return {boolean} a private WP.com blog flag
+ */
+export const getIsBlogPrivate = () =>
+	typeof window === 'object' &&
+	window.wpcomGutenberg &&
+	Number( window.wpcomGutenberg.blogPublic ) === -1;
```
Comment (retrofox) [inline src/blocks/homepage-articles/helpers.js]: Are we agree that `Number( window.wpcomGutenberg.blogPublic )` will be `NaN` if blogPublig is not defined?
Maybe it worths check if blogPublic is defined, too:

```es6
export const getIsBlogPrivate = () =>
	typeof window === 'object' &&
	window.wpcomGutenberg &&
	window.wpcomGutenberg.blogPublic &&
	Number( window.wpcomGutenberg.blogPublic ) === -1;
```

File: src/blocks/homepage-articles/edit.js (hunk 5 above)
Comment (WunderBart) [reply src/blocks/homepage-articles/edit.js]: TIL, thanks!

File: src/blocks/homepage-articles/helpers.js (hunk 6 above)
Comment (WunderBart) [reply src/blocks/homepage-articles/helpers.js]: IMO, it's not necessary - `Number()` will not throw error no matter what type of value we put there. `NaN === -1` is still a valid comparison and returns expected value.

**Comment by retrofox** [comment]
Just a simple note: the value of the `blogPublic` property is a string, so in the testing instructions is should be `window.wpcomGutenberg.blogPublic = "-1"`

**Comment by retrofox** [comment]
Just a simple note: the value of the `blogPublic` property is a string, so in the testing instructions is should be `window.wpcomGutenberg.blogPublic = "-1"`

**Comment by obenland** [comment]
@jeffersonrabb Do you think this PR would be worth a new .26 release?

**Comment by jeffersonrabb** [comment]
> @jeffersonrabb Do you think this PR would be worth a new .26 release?

Yeah, although I'm going to do a quick pass through recent issues to see if there's any other low hanging fruit. Either way we'll do a .26 release tomorrow.
